config/routes.rb
Rails.application.routes.draw do
  resources :appearances, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :guests, only: [:index, :show]
  resources :episodes, only: [:index, :show]
end

app/models/appearance.rb
class Appearance < ApplicationRecord
  belongs_to :guest
  belongs_to :episode

  validates :rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  # validates :rating, presence: true 
  # validates :episode_id, presence: true 
  # validates :guest_id, presence: true 
end

app/models/apperance.rb
class Apperance < ApplicationRecord
  belongs_to :episode
  belongs_to :guest

  validates :guest_rating, inclusion: { in: 1..5 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
    has_many :appearances
    has_many :guests, through: :appearances
end

app/models/guest.rb
class Guest < ApplicationRecord
    has_many :appearances
    has_many :episodes, through: :appearances
end

app/controllers/appearance_controller.rb
class AppearanceController < ApplicationController

  def new
    @appearance = Appearance.new
  end

  def create
    # byebug

    @appearance = Appearance.new(appearance_params)
    if @appearance.valid?
        @appearance.save
        redirect_to episode_path(@appearance.episode_id)
    else
        redirect_to new_appearance_path
    end

  end

  private
    def appearance_params
      params.require(:appearance).permit(:episode_id, :guest_id, :rating)
    end

end

app/controllers/appearances_controller.rb
class AppearancesController < ApplicationController

    def new
        @appearance = Appearance.new
    end 

    def create
        @appearance = Appearance.create(appearance_params)

        if @appearance.valid?
            redirect_to episode_path(appearance_params[:episode_id])
        else
            flash[:errors] = @appearance.errors.full_messages
            redirect_to new_appearance_path
        end 

        
    end 

    private

    def appearance_params
        params.require(:appearance).permit(:rating, :guest_id, :episode_id)
    end 
end

app/controllers/apperances_controller.rb
class ApperancesController < ApplicationController
  def new
    @apperance = Apperance.new
    @guests = Guest.all
    @episodes = Episode.all
  end

  def create
    apperance = Apperance.create(apperance_params)
    if apperance.valid?
      redirect_to apperance.episode
    else
      flash[:error] = "Sorry-- invalid rating"
      redirect_to new_apperance_path
    end
  end

  private
  def apperance_params
    params.require(:apperance).permit(:guest_id, :episode_id, :guest_rating)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @episodes = Episode.all
  end

  def show
    @episode = Episode.find(params[:id])
  end 
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def get_guest
    @guest = Guest.find(params[:id])
  end 

  def index
    @guests = Guest.all
  end

  def show
    get_guest
  end 

end

app/helpers/appearances_helper.rb
module AppearancesHelper
end

app/helpers/apperances_helper.rb
module ApperancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/appearance/new.html.erb
<h1> Create an Appearance: </h1><br>
<%= form_for(@appearance) do |f| %>

 <%#=collection_select(:person, :city_id, City.all, :id, :name) %>

<%= collection_select(:appearance, :episode_id, Episode.all, :id, :number) %>
<br>
<br>
<%= collection_select(:appearance, :guest_id, Guest.all, :id, :name) %>
<br>
<br>
<%= f.label :rating, "rate pls" %>
<%= f.number_field :rating %>
<br>
<Br>
<%= f.submit %>

<% end %>

app/views/appearances/_appearance_form.html.erb
<%= form_for @appearance do |f| %>

	<%= f.label :guest_rating %>
	<%= f.number_field :guest_rating, min: 1, max: 5 %>
	<br>
	<%= f.label :guest_id %>
	<%= f.collection_select(:guest_id, Guest.all, :id, :name, prompt: true) %>
	<br>
	<%= f.label :episode_id %>
	<%= f.collection_select(:episode_id, Episode.all, :id, :date, prompt: true) %>
	<br>
	<%= f.submit %>
	<br>
<% end %>

app/views/appearances/index.html.erb
<h1>All Appearances</h1>

<ul>
  <% @appearances.each do |appearance| %>
    <li><%= appearance.guest.name %></li>
    <li><%= appearance.episode.date %></li>
    <%= link_to "Appearance", appearance %>
  <% end %>
</ul>

app/views/appearances/new.erb
<h1>
    Create a new Apperance
</h1>

<%if flash[:errors] %>
    <%flash[:errors].each do |err|%>
       <li><%= err %></li>
    <% end %> 
<% end %>

<%= form_for @appearance do |f|%>

    <%= f.label :guest_id %> <br>
    <%= f.collection_select :guest_id, Guest.all, :id, :name, prompt: true %><br>

    <%= f.label :episode_id %><br>
    <%= f.collection_select :episode_id, Episode.all, :id, :number, prompt: true %><br>

    <%= f.label :rating %><br>
    <%= f.number_field :rating %><br>

    <%= f.submit %>
<% end %>

app/views/appearances/new.html.erb
<h1>Guest Appearance Form</h1>
<%= form_for @appearance do |f| %>    
    <%= f.collection_select :guest_id, @guests, :id, :name %>

    <%= f.number_field :guest_rating %>

    <%= f.collection_select :episode_id, @episodes, :id, :date %>

    <%= f.submit %>
<%end %>

app/views/appearances/show.html.erb
<h1>Appearance</h1>

<h2> <%= @appearance.guest.name %> </h2>
<h2> <%= @appearance.episode.date %> </h2>

app/views/apperances/new.html.erb
<% if flash[:error] %>
  <%= content_tag :h1, flash[:error] %>
<% end %>

<%= form_for @apperance do |f| %>
  <%= f.label :guest %>
  <%= f.collection_select :guest_id, @guests, :id, :name %><br />
  <%= f.label :episode %>
  <%= f.collection_select :episode_id, @episodes, :id, :number %><br />
  <%= f.label :rating %>
  <%= f.select :guest_rating, 1..5 %></br>
  <%= f.submit %>
<% end %>

app/views/episodes/index.html.erb
<h1>All Episodes</h1>

<ul>
  <% @episodes.each do |episode| %>
    <li><%= link_to "Episode #{episode.number} - #{episode.date.strftime("%B %d, %Y")}", episode_path(episode)%></li>
  <% end %>
</ul>

app/views/episodes/new.html.erb
<h1>New Episode</h1>


<% if flash[:errors] %>
    <% flash[:errors].each do |err| %>
        <li><%= err %></li>
    <% end %>
<% end %>
<br>

<%= form_for @episode do |f| %>
    <%= f.label :date %>
    <%= f.date_select :date %>
    <%= f.hidden_field :number, value: Episode.all.count + 1 %>
    <%= f.submit %>
<% end %>

app/views/episodes/show.erb
<h1>
   <%= "Episode ##{@episode.number}" %>
</h1>

<% @episode.guests.each do |guest|%>
   <li> <%= guest.name %> </li>
<% end %>

app/views/episodes/show.html.erb
<h1>These are the details for <%=@episode.number%></h1>

Date: <%=@episode.date%> <br>
Episode Number: <%=@episode.number%> <br>
<h1>Episode Guests</h1>
<%@episode.guests.each do |guest|%>
<%=guest.name%><br>
<%end%>

app/views/guests/edit.html.erb
<h1>Edit Guest Info! </h1>

<%= form_for @guest, :action => "update"  do |f| %>
    <%= f.label :name, "Enter the Guest Name:" %>
    <%= f.text_field :name, required: true %>
    <br><br>
    <%= f.label :occupation, "Enter the Guest Occupation:" %>
    <%= f.text_field :occupation, required: true %>
    <br><br>
    <%= f.submit "Edit This Entry!" %>
<% end %>

app/views/guests/index.html.erb
<h1>All The Guests</h1>

<ul>
  <% @guests.each do |guest| %>
    <li><%= link_to guest.name, guest_path(guest) %></li>
  <% end %>
</ul>

app/views/guests/new.html.erb
<%= form_for @guest do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :name %>
<%= f.text_field :occupation %>
<%= f.label :occupation %>
<%= f.submit "create new guest" %>

<= end %>

app/views/guests/show.erb
<h1>
    <%= @guest.name %>
</h1>
<br>


<%= @guest.occupation %>

app/views/guests/show.html.erb
<h1> Meet our guests!</h1>
<h3><%= @guest.name %> </h3>
<p> <%= @guest.occupation %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImmersiveRailsAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>